// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioPreview: typeof import('./components/uploadingfiles/AudioPreview.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    Creator: typeof import('./components/Creator.vue')['default']
    DragAndDrop: typeof import('./components/uploadingfiles/DragAndDrop.vue')['default']
    DragAndDropInstant: typeof import('./components/uploadingfiles/DragAndDropInstant.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileProgress: typeof import('./components/uploadingfiles/FileProgress.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    'Home - AbstractIspod': typeof import('./components/Home - AbstractIspod.vue')['default']
    'Home - AbstractIspod (copy 1)': typeof import('./components/Home - AbstractIspod (copy 1).vue')['default']
    'Home - AbstractSaStrane': typeof import('./components/Home - AbstractSaStrane.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    MultipleFiles: typeof import('./components/uploadingfiles/MultipleFiles.vue')['default']
    MultipleImagesPreview: typeof import('./components/uploadingfiles/MultipleImagesPreview.vue')['default']
    MyReview: typeof import('./components/MyReview.vue')['default']
    Navigacija: typeof import('./components/Navigacija.vue')['default']
    OldPdfV: typeof import('./components/oldPdfV.vue')['default']
    PdfViewer: typeof import('./components/PdfViewer.vue')['default']
    PlayVideo: typeof import('./components/PlayVideo.vue')['default']
    PreviewCsv: typeof import('./components/uploadingfiles/PreviewCsv.vue')['default']
    Proba: typeof import('./components/Proba.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleFile: typeof import('./components/uploadingfiles/SingleFile.vue')['default']
    SingleImagePreview: typeof import('./components/uploadingfiles/SingleImagePreview.vue')['default']
    TitleRefresh: typeof import('./components/TitleRefresh.vue')['default']
    Uploader: typeof import('./components/uploadingfiles/Uploader.vue')['default']
    Uploader2: typeof import('./components/uploadingfiles/Uploader2.vue')['default']
    VideoPreview: typeof import('./components/uploadingfiles/VideoPreview.vue')['default']
  }
}

export {}
